DO
$$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'root') THEN
CREATE ROLE root LOGIN PASSWORD 'root';
ALTER ROLE root WITH SUPERUSER;
END IF;
END
$$;

GRANT CONNECT ON DATABASE appdb TO root;